<?xml version="1.0" encoding="utf-8"?><Database Name="LINQ_SQL" Class="LINQ_SQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-14LTTDV\SQLEXPRESS;Initial Catalog=LINQ_SQL;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="Linq_Sql.Properties.Settings" SettingsPropertyName="LINQ_SQLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="std" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>